# Generated by Django 4.1.1 on 2022-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(verbose_name='id')),
                ('ResultTypeID', models.IntegerField(verbose_name='ResultTypeID')),
                ('TestName', models.IntegerField(verbose_name='TestName')),
            ],
        ),
    ]
